### PR TITLE
updated new template

### PR DESCRIPTION
**Pull request by gkiar**
Notes:

- entries are, instead of being assigned to a section by being stated explicitly, assigned to a section based on the entry type. That means under review articles have different bib headings than published, etc., but all entry information can remain the same
- the bib must be compiled with `biber` rather than `bibtex`
- compilations requires lualatex, biber, then lualatex, to generate full document.

### CODE REVIEW

**Comment by gkiar** [comment]
you can view an example at: https://github.com/gkiar/cv/raw/master/gkiarcv.pdf

**Comment by jovo** [comment]
cool, i can't merge though because there are two conflicting files?

**Comment by jovo** [comment]
ps - yours looks sgreat!

"To the Cloud" is in a peer-reviewed journal, but it is not peer-reviewed. i'd be more clear about that.

also, enumeration is key for articles and such.  is there a way to enumerate here?

**Comment by gkiar** [comment]
Good call! I specified it was a requested article, and I added bib enumeration.

**Comment by gkiar** [comment]
Also, I don't think you even _should_ merge this, rather it's a pointer so that a ugrad you hire can scrape my template and reformat your `.bib` and `.tex` files accordingly. It requires a substantial number of trivially difficult changes in both files to successfully transition to this new format.

**Pull request closed without merging**
